language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.1
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit # latest stable version (2.0.3)
    - LUA=luajit2.0 # current head of 2.0 branch
    - LUA=luajit2.1 # current head of 2.1 branch

cache:
  - apt
  - /usr/local/share/lua

before_install:
  - source .travis/setenv_lua.sh

install:
  - apt-get install -qq libev-dev libssl-dev
  - luarocks install moonscript
  - luarocks install busted
  # for coveralls
  - luarocks install luasocket
  - luarocks install luasec 0.4.1-2 OPENSSL_DIR=/usr OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu
  - luarocks install luafilesystem
  - luarocks install copas
  - luarocks install lua-ev
  - luarocks install luajson

script:
  - make ci
