language: erlang

env:
  - LUA="luajit-2.0.2"

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq git luajit love luarocks libev-dev make
  - sudo ln -s /usr/bin/luajit-2.0.0-beta9 /usr/bin/luajit
  - sudo luarocks install luafilesystem
  - sudo luarocks install copas
  - sudo luarocks install moonscript
  - sudo luarocks install lua-ev

script: "sudo make test"