language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.1
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit # latest stable version (2.0.3)
    - LUA=luajit2.0 # current head of 2.0 branch
    # currently broken, but doesn't really matter for Love2d
    #- LUA=luajit2.1 # current head of 2.1 branch


cache:
  - apt
  - /usr/local/share/lua

before_install:
  - source .travis/setenv_lua.sh
  - luarocks install luacov-coveralls
  - luarocks install Lua-cURL
  - luarocks install busted
  - luarocks install moonscript

script:
  - make ci

after_success:
  - luacov-coveralls -i "%.moon" -e "tests"
