language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.1
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit # latest stable version (2.0.3)
    - LUA=luajit2.0 # current head of 2.0 branch
    - LUA=luajit2.1 # current head of 2.1 branch

cache:
  - apt
  - /usr/local/share/lua

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install moonscript
  - luarocks install busted
  # for coveralls
  - luarocks install luasec    # To send request
  - luarocks install luajson

script:
  - make ci
