#!/bin/sh
echo "-- Autogenerated with $0 on $(command date +"%F %T")" > LovePunk/everything.moon
find LovePunk -iname "*.moon" | sed -e "s,/,.,g" -e "s/\.moon$//" | awk '{ print "require \""$1"\""}' | grep -v "everything" | sort >> LovePunk/everything.moon
