-- Busted mock for Löve 0.8.0

require "busted"

local loveTbl = {
  _modules = {
    joystick = nil,
    audio = nil,
    keyboard = nil,
    event = nil,
    thread = nil,
    physics = nil,
    filesystem = nil,
    font = nil,
    graphics = nil,
    timer = nil,
    mouse = nil,
    sound = nil,
    image = nil,
  },
  keyboard = {
    setKeyRepeat = function() end,
    getKeyRepeat = function() end,
    isDown = function() end,
  },
  boot = function() end,
  image = {
    newImageData = function() end,
  },
  _version_codename = 'Rubber Piggy',
  handlers = {
    joystickreleased = function() end,
    quit = function() end,
    joystickpressed = function() end,
    focus = function() end,
    keypressed = function() end,
    keyreleased = function() end,
    mousereleased = function() end,
    mousepressed = function() end,
  },
  sound = {
    newDecoder = function() end,
    newSoundData = function() end,
  },
  joystick = {
    getAxes = function() end,
    getNumBalls = function() end,
    getAxis = function() end,
    getNumAxes = function() end,
    getName = function() end,
    close = function() end,
    getNumJoysticks = function() end,
    open = function() end,
    isDown = function() end,
    getNumHats = function() end,
    getBall = function() end,
    isOpen = function() end,
    getNumButtons = function() end,
    getHat = function() end,
  },
  init = function() end,
  _exe = 'true',
  font = {
    newRasterizer = function() end,
    newGlyphData = function() end,
  },
  timer = {
    sleep = function() end,
    getDelta = function() end,
    getMicroTime = function() end,
    getFPS = function() end,
    step = function() end,
    getTime = function() end,
  },
  arg = {
    parse_option = function() end,
    getLow = function() end,
    options = {
      game = {
        a = '1',
        arg = {
          "tmp",
        },
        set = 'true',
      },
      console = {
        a = '0',
      },
    },
    parse_options = function() end,
  },
  _version = '0.8.0',
  path = {
    normalslashes = function() end,
    leaf = function() end,
    abs = function() end,
    getfull = function() end,
    endslash = function() end,
  },
  _version_major = '0',
  thread = {
    getThreads = function() end,
    getThread = function() end,
    newThread = function() end,
  },
  _os = 'Linux',
  errhand = function() end,
  _version_revision = '0',
  nogame = function() end,
  physics = {
    newCircleShape = function() end,
    newFixture = function() end,
    newMouseJoint = function() end,
    newWeldJoint = function() end,
    newDistanceJoint = function() end,
    newWorld = function() end,
    newRevoluteJoint = function() end,
    newWheelJoint = function() end,
    setMeter = function() end,
    newRectangleShape = function() end,
    newFrictionJoint = function() end,
    newBody = function() end,
    getMeter = function() end,
    newGearJoint = function() end,
    newChainShape = function() end,
    getDistance = function() end,
    newRopeJoint = function() end,
    newPulleyJoint = function() end,
    newPrismaticJoint = function() end,
    newEdgeShape = function() end,
    newPolygonShape = function() end,
  },
  _curthread = nil,
  run = function() end,
  releaseerrhand = function() end,
  createhandlers = function() end,
  filesystem = {
    getAppdataDirectory = function() end,
    newFile = function() end,
    getWorkingDirectory = function() end,
    remove = function() end,
    setRelease = function() end,
    isDirectory = function() end,
    getSaveDirectory = function() end,
    setIdentity = function() end,
    write = function() end,
    init = function() end,
    isFile = function() end,
    newFileData = function() end,
    setSource = function() end,
    getLastModified = function() end,
    read = function() end,
    exists = function() end,
    getUserDirectory = function() end,
    lines = function() end,
    enumerate = function() end,
    load = function() end,
    mkdir = function() end,
  },
  _version_compat = {
    "0.8.0",
  },
  graphics = {
    getFont = function() end,
    getColorMode = function() end,
    isCreated = function() end,
    setIcon = function() end,
    getMaxPointSize = function() end,
    setCaption = function() end,
    checkMode = function() end,
    getScissor = function() end,
    newPixelEffect = function() end,
    _transformGLSLErrorMessages = function() end,
    newQuad = function() end,
    drawTest = function() end,
    reset = function() end,
    setLineWidth = function() end,
    present = function() end,
    setPointSize = function() end,
    newImageFont = function() end,
    getPointSize = function() end,
    getColor = function() end,
    shear = function() end,
    setScissor = function() end,
    getLineStyle = function() end,
    clear = function() end,
    setInvertedStencil = function() end,
    setLineStyle = function() end,
    draw = function() end,
    getLineWidth = function() end,
    toggleFullscreen = function() end,
    getMode = function() end,
    newCanvas = function() end,
    setMode = function() end,
    setNewFont = function() end,
    triangle = function() end,
    print = function() end,
    getModes = function() end,
    isSupported = function() end,
    setPoint = function() end,
    newImage = function() end,
    newSpriteBatch = function() end,
    _effectCodeToGLSL = function() end,
    newScreenshot = function() end,
    newStencil = function() end,
    getCanvas = function() end,
    newFont1 = function() end,
    point = function() end,
    arc = function() end,
    polygon = function() end,
    rotate = function() end,
    hasFocus = function() end,
    setColor = function() end,
    translate = function() end,
    scale = function() end,
    getBackgroundColor = function() end,
    pop = function() end,
    push = function() end,
    setPixelEffect = function() end,
    circle = function() end,
    quad = function() end,
    rectangle = function() end,
    line = function() end,
    newFont = function() end,
    getWidth = function() end,
    setLine = function() end,
    getBlendMode = function() end,
    setDefaultImageFilter = function() end,
    getCaption = function() end,
    setCanvas = function() end,
    setBlendMode = function() end,
    getHeight = function() end,
    setStencil = function() end,
    printf = function() end,
    setFont = function() end,
    printf1 = function() end,
    setPointStyle = function() end,
    print1 = function() end,
    newParticleSystem = function() end,
    getDefaultImageFilter = function() end,
    getPointStyle = function() end,
    drawq = function() end,
    getPixelEffect = function() end,
    setBackgroundColor = function() end,
    setColorMode = function() end,
  },
  audio = {
    rewind = function() end,
    getVolume = function() end,
    getNumSources = function() end,
    setDistanceModel = function() end,
    getOrientation = function() end,
    setPosition = function() end,
    newSource1 = function() end,
    setOrientation = function() end,
    play = function() end,
    setVelocity = function() end,
    newSource = function() end,
    getDistanceModel = function() end,
    stop = function() end,
    resume = function() end,
    getPosition = function() end,
    setVolume = function() end,
    pause = function() end,
    getVelocity = function() end,
  },
  mouse = {
    isVisible = function() end,
    getX = function() end,
    setGrab = function() end,
    setPosition = function() end,
    setVisible = function() end,
    isGrabbed = function() end,
    isDown = function() end,
    getPosition = function() end,
    getY = function() end,
  },
  _version_minor = '8',
  event = {
    poll = function() end,
    push = function() end,
    quit = function() end,
    pump = function() end,
    clear = function() end,
    wait = function() end,
  },
}
love = mock(loveTbl)
return love
